name: CI/CD Firebase Functions sub_motherboard_sendNotification

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Seleccione el entorno'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      # 1️⃣ Checkout
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Build
      - name: Build
        run: npm run build

      # 5️⃣ Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 6️⃣ Setup Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gcloud'

      # 7️⃣ Deploy to Firebase
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions:sub_motherboard_sendNotification --project ${{ secrets.GCP_PROJECT_ID }}